# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=20)),
                ('uploaded_TM', models.DateTimeField(auto_now_add=True)),
                ('last_view_TM', models.DateTimeField()),
                ('isFavor', models.BooleanField()),
                ('bucketPath', models.CharField(max_length=50)),
                ('fileSize', models.IntegerField()),
                ('localPath', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_name', models.CharField(max_length=30)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='fileshell.Folder')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ManyToManyField(blank=True, null=True, related_name='datas', to='fileshell.Folder'),
        ),
    ]
